######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 14 01:33:10 2013
######################################################################

TARGET = vkbd
TEMPLATE = app

greaterThan(QT_MAJOR_VERSION, 4) {
    QT += widgets multimedia
}

SOURCES += keyboard.cpp main.cpp

HEADERS += en_keymap.h keyboard.h

FORMS += keyboard.ui









